apiVersion: apps/v1
kind: Deployment
metadata:
  name: gearapp-deploy
  labels:
    app: gearapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gearapp

  template:
    metadata:
      labels:
        app: gearapp
    spec:
      containers:
      - name: gearapp
        image: shivareddi/gearapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

